on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Windows
permissions:
  id-token: write
  contents: read
env:
  BUILD_TYPE: Release
  GITHUB_ACTIONS: true
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - name: "Build on x64"
          os: windows-latest
      fail-fast: false
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Vcpkg"
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: boost-locale curl gettext gettext-libintl gtest jsoncpp maddy sqlcipher
          triplet: x64-windows
          cache-key: ${{ matrix.config.os }}
          revision: 64e15f6669480b2d2bff1e5e815c571a8213421e
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "CMake Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake -G "Visual Studio 17 2022" ..
          cmake --build . --config ${{env.BUILD_TYPE}}
      - name: "CMake Install"
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --prefix "${{github.workspace}}/install"
      - name: "CMake Test"
        run: ${{github.workspace}}/build/Release/libaura_test.exe
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/install
          name: Windows-x64-${{env.BUILD_TYPE}}
