on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Windows
permissions:
  id-token: write
  contents: read
env:
  BUILD_TYPE: Release
  GITHUB_ACTIONS: true
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - name: "Build on x64"
          os: windows-latest
          artifact: "Windows-x64"
      fail-fast: false
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "Get Conan"
        uses: turtlebrowser/get-conan@main
      - name: "Install Conan"
        run: |
          move conan/conanfile-windows.txt conanfile.txt
          move conan/conanprofile-windows.txt conanprofile.txt
          conan install conanfile.txt --profile:host=conanprofile.txt --profile:build=conanprofile.txt -s compiler.cppstd=20 --build=missing
      - name: "CMake Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/build/generators/conan_toolchain.cmake"
          cmake --build . --config ${{env.BUILD_TYPE}}
      - name: "CMake Install"
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --prefix "${{github.workspace}}/install"
      - name: "CMake Test"
        working-directory: ${{github.workspace}}/build/Release
        run: libaura_test.exe
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/install
          name: ${{matrix.config.artifact}}-${{env.BUILD_TYPE}}
